const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  REDUCE_ITEM: "REDUCE_ITEM",
  CLEAR_CART: "CLEAR_CART",
};

export default CartActionTypes;
